### PR TITLE
Prevent a screen flicker during navigation on dark mode

### LINKED ISSUE #138: Transition flashes to white in Dark Mode
### Describe the bug
In Dark Mode when transitioning from one screen to the other, the screen fades to white which effectively makes a short flash.

### To Reproduce
1. Use tge app with Dark Mode enabled
2. Click on any unselected bottom tab

### Expected behavior
shouldn't flash like that, and should instead fade to black when in black mode

### Smartphone
 - OS: Android11

### PR DESCRIPTION
**Pull request by domi41**
Fixes #138 

From : https://stackoverflow.com/questions/71108210/screens-are-flashing-when-i-navigate-to-them-in-dark-theme-using-navigation-comp/77248016#77248016

### CODE REVIEW

File: app/src/main/java/com/illiouchine/jm/MainActivity.kt [hunk 1]
```diff
@@ -72,146 +73,148 @@ class MainActivity : ComponentActivity() {
...
-                            navigator = navigator,
-                            homeViewState = homeViewState,
-                            onDeletePoll = homeViewModel::deletePoll,
-                            onSetupBlankPoll = homeViewModel::setupBlankPoll,
-                            onSetupClonePoll = homeViewModel::clonePoll,
-                            onResumePoll = homeViewModel::resumePoll,
-                            onShowResult = homeViewModel::showResult,
-                        )
-                    }
+                Surface {  // Using a Surface here prevents a screen flicker when navigating.
```
Comment (domi41) [inline app/src/main/java/com/illiouchine/jm/MainActivity.kt:76]: The diff is misleading ; this is the only change of this commit.
